### ISSUE TITLE
《亲密接触人工智能――从零搭建对话机器人》这本书有电子版发售吗？

### ISSUE THREAD

**Issue by rawbean** [debiaozhou/book_for_chatbot#3]
Dear 周先生，
         《亲密接触人工智能――从零搭建对话机器人》这本新书书挺不错的，我第一时间购买了。但因为纸质不方便，希望购买电子版的，但似乎没有找到书店售卖，这里咨询现在有电子版发售吗？

**Comment by debiaozhou** [comment]
非常抱歉，目前出版社只有纸质版发售。

**Comment by rawbean** [comment]
收到，谢谢！
